#ifndef QPOP3CLIENT_GLOBAL_H
#define QPOP3CLIENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QPOP3CLIENT_LIBRARY)
#  define QPOP3CLIENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QPOP3CLIENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QPOP3CLIENT_GLOBAL_H
